---
name: Deploy

on:
  push:
    tags:
      - '*'

env:
  PROJECT_ID: personal-419019
  IMAGE_NAME: europe-west1-docker.pkg.dev/personal-419019/pantry/api:${{ github.ref_name }}

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Auth with Google Cloud
        id: auth
        uses: google-github-actions/auth@v2
        with:
          credentials_json: "${{ secrets.GOOGLE_SERVICE_ACCOUNT_KEY }}"
      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: ${{ env.PROJECT_ID }}
      - name: Auth with Docker
        run: gcloud auth configure-docker europe-west1-docker.pkg.dev --quiet
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          tags: ${{ env.IMAGE_NAME }}
          push: true
  deploy:
    runs-on: ubuntu-22.04
    needs: build
    steps:
      - name: Auth with Google Cloud
        id: auth
        uses: google-github-actions/auth@v2
        with:
          credentials_json: "${{ secrets.GOOGLE_SERVICE_ACCOUNT_KEY }}"
      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: ${{ env.PROJECT_ID }}
      - name: Deploy
        run: gcloud run deploy pantry-api --image=$IMAGE_NAME --region europe-west1
